# Generated by Django 5.1.2 on 2024-11-27 22:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyCard',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_status', models.PositiveSmallIntegerField(choices=[(0, 'Активирована'), (1, 'Заблокирована')], default=0, verbose_name='Тип товара')),
                ('bonuses', models.PositiveIntegerField(default=0, verbose_name='Количество бонусов')),
            ],
            options={
                'verbose_name': 'Карта лояльности',
                'verbose_name_plural': 'Карты лояльности',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_end_promotion', models.DateTimeField(verbose_name='Время конца скидки')),
                ('promotion_percentage', models.SmallIntegerField(verbose_name='Процент скидки')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_buy', models.DateField(null=True, verbose_name='Время покупки')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Купил за сумму')),
                ('paid_with_bonuses', models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Оплачено бонусами')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Покупка состоялась')),
                ('goods_is_received', models.BooleanField(default=False, verbose_name='Товар получен')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
            },
        ),
        migrations.CreateModel(
            name='PurchaseGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=1, verbose_name='Количество для покупки')),
            ],
            options={
                'verbose_name': 'В покупке',
                'verbose_name_plural': 'Товары в покупках',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1024, unique=True, verbose_name='Название товара')),
                ('photo', models.ImageField(default='default/goods.png', upload_to='goods/%Y/%m/%d/', verbose_name='Фотография')),
                ('type_goods', models.PositiveSmallIntegerField(choices=[(0, 'Другое'), (1, 'Лекарство'), (2, 'Медицинские изделия'), (3, 'Косметика'), (4, 'Гигиена'), (5, 'Добавки/Витамины')], default=0, verbose_name='Тип товара')),
                ('goods_info', models.CharField(max_length=2048, verbose_name='Информация о товаре')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('amount_in_stock', models.PositiveSmallIntegerField(default=0, verbose_name='Количество в наличие')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='price_goods_CK')],
            },
        ),
        migrations.CreateModel(
            name='GoodsReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Время написания')),
                ('date_change', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('message', models.TextField(max_length=4096, verbose_name='Сообщение')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Оценка')),
                ('goods_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_review_fk', to='pharmacy.goods', verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
