# Generated by Django 5.1.2 on 2024-12-08 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreview',
            name='wrote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_wrote', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='loyaltycard',
            name='user_card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_card_fk', to=settings.AUTH_USER_MODEL, verbose_name='card of user'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='promotion_goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_goods_fk', to='pharmacy.goods', verbose_name='promotion goods'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='user_buy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_buy_fk', to=settings.AUTH_USER_MODEL, verbose_name='buyer'),
        ),
        migrations.AddField(
            model_name='purchasegoods',
            name='goods_purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_purchase_fk', to='pharmacy.goods', verbose_name='goods in purchase'),
        ),
        migrations.AddField(
            model_name='purchasegoods',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_fk', to='pharmacy.purchase', verbose_name='purchase'),
        ),
        migrations.AddConstraint(
            model_name='goodsreview',
            constraint=models.CheckConstraint(condition=models.Q(('grade__gte', 0.0), ('grade__lte', 5.0)), name='grade_CK'),
        ),
        migrations.AlterUniqueTogether(
            name='goodsreview',
            unique_together={('goods_review', 'wrote')},
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(condition=models.Q(('promotion_percentage__gte', 10), ('promotion_percentage__lte', 90)), name='promotion_percentage_CK'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(('total_price__gte', 0)), name='price_purchase_CK'),
        ),
        migrations.AddConstraint(
            model_name='purchasegoods',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 1)), name='purchase_amount_CK'),
        ),
        migrations.AlterUniqueTogether(
            name='purchasegoods',
            unique_together={('purchase', 'goods_purchase')},
        ),
    ]
