# Generated by Django 5.1.2 on 2024-12-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=1024, unique=True, verbose_name='title')),
                ('text', models.TextField(max_length=32768, verbose_name='text')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='time of writing')),
                ('date_change', models.DateTimeField(auto_now=True, verbose_name='time of change')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'draft'), (1, 'published'), (2, 'deleted')], default=0, verbose_name='status')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='time of creation')),
                ('date_change', models.DateTimeField(auto_now=True, verbose_name='time of last change')),
                ('message', models.TextField(max_length=4096, verbose_name='message')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'displayed'), (1, 'deleted')], default=0, verbose_name='status')),
            ],
            options={
                'verbose_name': 'comment on the post',
                'verbose_name_plural': 'comments on posts',
            },
        ),
        migrations.CreateModel(
            name='PostGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'goods of the post',
                'verbose_name_plural': 'goods of posts',
            },
        ),
        migrations.CreateModel(
            name='SubscriberBlogUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
            },
        ),
    ]
