# Generated by Django 5.1.2 on 2024-11-27 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        ('pharmacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='wrote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wrote_fk', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='comment_in_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_in_post_fk', to='blog.post', verbose_name='Комментарий под постом'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='wrote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_wrote', to=settings.AUTH_USER_MODEL, verbose_name='Написал'),
        ),
        migrations.AddField(
            model_name='postgoods',
            name='goods_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_post_fk', to='pharmacy.goods', verbose_name='Товар поста'),
        ),
        migrations.AddField(
            model_name='postgoods',
            name='post_with_goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_with_goods_fk', to='blog.post', verbose_name='Пост с товарами'),
        ),
        migrations.AddField(
            model_name='subscriberbloguser',
            name='blogger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blogger_fk', to=settings.AUTH_USER_MODEL, verbose_name='Подписан на'),
        ),
        migrations.AddField(
            model_name='subscriberbloguser',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriber_fk', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик'),
        ),
        migrations.AlterUniqueTogether(
            name='postgoods',
            unique_together={('goods_post', 'post_with_goods')},
        ),
        migrations.AlterUniqueTogether(
            name='subscriberbloguser',
            unique_together={('blogger', 'subscriber')},
        ),
    ]
