# Generated by Django 5.1.2 on 2024-12-08 11:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='award/%Y/%m/%d/', verbose_name='image of the award')),
                ('description', models.TextField(blank=True, max_length=512, verbose_name='description award')),
            ],
            options={
                'verbose_name': 'award',
                'verbose_name_plural': 'awards',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', models.ImageField(default='default/avatar.png', upload_to='users/avatars/%Y/%m/%d/', verbose_name='user avatar')),
                ('background', models.ImageField(default='default/background.png', upload_to='users/backgrounds/%Y/%m/%d/', verbose_name='profile background')),
                ('about', models.TextField(blank=True, max_length=512, verbose_name='about user')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='user balance')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AwardsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_awarded', models.DateTimeField(auto_now_add=True, verbose_name='award time')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_fk', to='user.awards', verbose_name='award')),
                ('award_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='award_user_fk', to=settings.AUTH_USER_MODEL, verbose_name='rewarded user')),
            ],
            options={
                'verbose_name': 'user award',
                'verbose_name_plural': 'user awards',
            },
        ),
        migrations.CreateModel(
            name='BanCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banned_date', models.DateTimeField(auto_now_add=True, verbose_name='when banned')),
                ('ban_time', models.DurationField(null=True, verbose_name='ban time')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('got_banned', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='got_banned_fk', to=settings.AUTH_USER_MODEL, verbose_name='got banned')),
                ('who_banned', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='who_banned_fk', to=settings.AUTH_USER_MODEL, verbose_name='who banned')),
            ],
            options={
                'verbose_name': 'communication ban',
                'verbose_name_plural': 'communication bans',
            },
        ),
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_black_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_black_list_fk', to=settings.AUTH_USER_MODEL, verbose_name='user in blacklist')),
                ('user_black_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_black_list_fk', to=settings.AUTH_USER_MODEL, verbose_name='user blacklist')),
            ],
            options={
                'verbose_name': 'blacklist_user',
                'verbose_name_plural': 'blacklist_users',
            },
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='friends_user_fk', to=settings.AUTH_USER_MODEL)),
                ('user_friend', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_friend_fk', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'friend',
                'verbose_name_plural': 'friends',
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=512, verbose_name='notification message')),
                ('date_notify', models.DateTimeField(auto_now_add=True, verbose_name='notification time')),
                ('viewed', models.BooleanField(default=False, verbose_name='viewed')),
                ('user_notify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notify_fk', to=settings.AUTH_USER_MODEL, verbose_name='notified user')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ('date_notify',),
            },
        ),
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='time of creation')),
                ('date_change', models.DateTimeField(auto_now=True, verbose_name='time of last change')),
                ('message', models.TextField(max_length=4096, verbose_name='message')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'displayed'), (1, 'deleted')], default=0, verbose_name='status')),
                ('it_read', models.BooleanField(default=False, verbose_name='read')),
                ('received', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_PM_fk', to=settings.AUTH_USER_MODEL, verbose_name='who received')),
                ('wrote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_wrote', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'private message',
                'verbose_name_plural': 'private messages',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_bloggers_in_blacklisted', models.BooleanField(default=False, verbose_name='do not display content from blacklisted users')),
                ('hide_yourself_subscriptions', models.BooleanField(default=False, verbose_name='hide subscriptions')),
                ('messages_from_friends_only', models.BooleanField(default=False, verbose_name='receive messages only from friends')),
                ('receive_notifications_about_discounts', models.BooleanField(default=False, verbose_name='receive notifications about discounts')),
                ('user_settings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings_fk', to=settings.AUTH_USER_MODEL, verbose_name='user settings')),
            ],
            options={
                'verbose_name': 'settings',
                'verbose_name_plural': 'settings',
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='balance_CK'),
        ),
        migrations.AlterUniqueTogether(
            name='blacklist',
            unique_together={('user_black_list', 'in_black_list')},
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('friends_user', 'user_friend')},
        ),
    ]
