# Generated by Django 5.1.2 on 2024-11-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_notifications_it_new_notifications_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='message',
            field=models.CharField(max_length=512, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='viewed',
            field=models.BooleanField(default=True, verbose_name='Просмотрено'),
        ),
    ]
