# Generated by Django 5.1.2 on 2024-11-14 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_notifications_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_seen',
        ),
        migrations.AlterField(
            model_name='settings',
            name='user_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings_fk', to=settings.AUTH_USER_MODEL),
        ),
    ]
