# Generated by Django 5.1.2 on 2024-11-14 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_is_online_remove_user_last_seen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='user_settings',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings_fk', to=settings.AUTH_USER_MODEL),
        ),
    ]
