# Generated by Django 5.1.2 on 2024-11-15 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_settings_user_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='messages_from_friends_only',
            field=models.BooleanField(default=False, verbose_name='Получать сообщения только от друзей'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='user_notify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notify_fk', to=settings.AUTH_USER_MODEL, verbose_name='Уведомляемый пользователь'),
        ),
    ]
